<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="0" skipped="64" tests="67" time="865.618"
        timestamp="2025-04-01T09:24:20.489949+00:00" hostname="9518f9e9ed12">
        <testcase classname="tests.jax.single_chip.models.albert_v2.base.test_albert_base"
            name="test_flax_albert_v2_base_inference" time="52.658">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_albert_v2_base_inference', 'specific_test_case': 'test_flax_albert_v2_base_inference', 'category': 'model_test', 'model_name': 'jax_albert_v2_base_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131036.078125. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.albert_v2.large.test_albert_large"
            name="test_flax_albert_v2_large_inference" time="19.231">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_albert_v2_large_inference', 'specific_test_case': 'test_flax_albert_v2_large_inference', 'category': 'model_test', 'model_name': 'jax_albert_v2_large_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131026.9375. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.albert_v2.xlarge.test_albert_xlarge"
            name="test_flax_albert_v2_xlarge_inference" time="22.195">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_albert_v2_xlarge_inference', 'specific_test_case': 'test_flax_albert_v2_xlarge_inference', 'category': 'model_test', 'model_name': 'jax_albert_v2_xlarge_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131030.6953125. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.albert_v2.xxlarge.test_albert_xxlarge"
            name="test_flax_albert_v2_xxlarge_inference" time="23.531">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_albert_v2_xxlarge_inference', 'specific_test_case': 'test_flax_albert_v2_xxlarge_inference', 'category': 'model_test', 'model_name': 'jax_albert_v2_xxlarge_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131022.7578125. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.alexnet.test_alexnet"
            name="test_alexnet_inference" time="5.117">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_alexnet_inference', 'specific_test_case': 'test_alexnet_inference', 'category': 'model_test', 'model_name': 'jax_alexnet_base_cv_image_cls_custom', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: error: failed to legalize operation 'stablehlo.pad'(https://github.com/tenstorrent/tt-xla/issues/360)" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bart.base.test_bart_base"
            name="test_flax_bart_base_inference" time="33.544">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_bart_base_inference', 'specific_test_case': 'test_flax_bart_base_inference', 'category': 'model_test', 'model_name': 'jax_bart_base_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=323375.3125. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bart.large.test_bart_large"
            name="test_flax_bart_large_inference" time="24.310">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_bart_large_inference', 'specific_test_case': 'test_flax_bart_large_inference', 'category': 'model_test', 'model_name': 'jax_bart_large_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=371601.96875. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.beit.base.test_beit_base"
            name="test_flax_beit_base_inference" time="5.200">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_beit_base_inference', 'specific_test_case': 'test_flax_beit_base_inference', 'category': 'model_test', 'model_name': 'jax_beit_base_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.beit.large.test_beit_large"
            name="test_flax_beit_large_inference" time="11.391">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_beit_large_inference', 'specific_test_case': 'test_flax_beit_large_inference', 'category': 'model_test', 'model_name': 'jax_beit_large_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bert.base.test_bert_base"
            name="test_flax_bert_base_inference" time="23.431">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_bert_base_inference', 'specific_test_case': 'test_flax_bert_base_inference', 'category': 'model_test', 'model_name': 'jax_bert_base_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131025.0078125. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bert.large.test_bert_large"
            name="test_flax_bert_large_inference" time="27.419">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_bert_large_inference', 'specific_test_case': 'test_flax_bert_large_inference', 'category': 'model_test', 'model_name': 'jax_bert_large_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131037.828125. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bloom.bloom_1b1.test_1b1"
            name="test_bloom_1b1_inference" time="52.816">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_bloom_1b1_inference', 'specific_test_case': 'test_bloom_1b1_inference', 'category': 'model_test', 'model_name': 'jax_bloom_1b1_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=12.176290512084961. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bloom.bloom_1b7.test_1b7"
            name="test_bloom_1b7_inference" time="50.077">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_bloom_1b7_inference', 'specific_test_case': 'test_bloom_1b7_inference', 'category': 'model_test', 'model_name': 'jax_bloom_1b7_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=25.83220100402832. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bloom.bloom_3b.test_3b"
            name="test_bloom_3b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_bloom_3b_inference', 'specific_test_case': 'test_bloom_3b_inference', 'category': 'model_test', 'model_name': 'jax_bloom_3b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/bloom/bloom_3b/test_3b.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bloom.bloom_560m.test_560m"
            name="test_bloom_560m_inference" time="25.877">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_bloom_560m_inference', 'specific_test_case': 'test_bloom_560m_inference', 'category': 'model_test', 'model_name': 'jax_bloom_560m_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=327.8369445800781. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.bloom.bloom_7b.test_7b"
            name="test_bloom_7b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_bloom_7b_inference', 'specific_test_case': 'test_bloom_7b_inference', 'category': 'model_test', 'model_name': 'jax_bloom_7b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/bloom/bloom_7b/test_7b.py:45:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.clip.base_patch16.test_clip_base_patch16"
            name="test_clip_base_patch16_inference" time="9.912">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_clip_base_patch16_inference', 'specific_test_case': 'test_clip_base_patch16_inference', 'category': 'model_test', 'model_name': 'jax_clip_vit_patch16_base_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.clip.base_patch32.test_clip_base_patch32"
            name="test_clip_base_patch32_inference" time="6.435">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_clip_base_patch32_inference', 'specific_test_case': 'test_clip_base_patch32_inference', 'category': 'model_test', 'model_name': 'jax_clip_vit_patch32_base_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.clip.large_patch14.test_clip_large_patch14"
            name="test_clip_large_patch14_inference" time="14.699">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_clip_large_patch14_inference', 'specific_test_case': 'test_clip_large_patch14_inference', 'category': 'model_test', 'model_name': 'jax_clip_vit_patch14_large_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.clip.large_patch14_336.test_clip_large_patch14_336"
            name="test_clip_large_patch14_336_inference" time="15.144">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_clip_large_patch14_336_inference', 'specific_test_case': 'test_clip_large_patch14_336_inference', 'category': 'model_test', 'model_name': 'jax_clip_vit_patch14_336_large_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.distilbert.test_distilbert"
            name="test_flax_distilbert_inference" time="12.950">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_distilbert_inference', 'specific_test_case': 'test_flax_distilbert_inference', 'category': 'model_test', 'model_name': 'jax_distilbert_uncased_base_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131036.078125. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt2.base.test_gpt2_base"
            name="test_gpt2_base_inference" time="12.640">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt2_base_inference', 'specific_test_case': 'test_gpt2_base_inference', 'category': 'model_test', 'model_name': 'jax_gpt2_base_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=37.821876525878906. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt2.large.test_gpt2_large"
            name="test_gpt2_large_inference" time="48.921">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt2_large_inference', 'specific_test_case': 'test_gpt2_large_inference', 'category': 'model_test', 'model_name': 'jax_gpt2_large_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=9.953690528869629. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt2.medium.test_gpt2_medium"
            name="test_gpt2_medium_inference" time="19.286">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt2_medium_inference', 'specific_test_case': 'test_gpt2_medium_inference', 'category': 'model_test', 'model_name': 'jax_gpt2_medium_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=13.961490631103516. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt2.xl.test_gpt2_xl"
            name="test_gpt2_xl_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt2_xl_inference', 'specific_test_case': 'test_gpt2_xl_inference', 'category': 'model_test', 'model_name': 'jax_gpt2_xl_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/gpt2/xl/test_gpt2_xl.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt_neo.gpt_neo_125m.test_gpt_neo_125m"
            name="test_gpt_neo_125m_inference" time="13.282">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt_neo_125m_inference', 'specific_test_case': 'test_gpt_neo_125m_inference', 'category': 'model_test', 'model_name': 'jax_gpt_neo_125m_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=15.864267349243164. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt_neo.gpt_neo_1_3b.test_gpt_neo_1_3b"
            name="test_gpt_neo_1_3b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt_neo_1_3b_inference', 'specific_test_case': 'test_gpt_neo_1_3b_inference', 'category': 'model_test', 'model_name': 'jax_gpt_neo_1.3b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/gpt_neo/gpt_neo_1_3b/test_gpt_neo_1_3b.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.gpt_neo.gpt_neo_2_7b.test_gpt_neo_2_7b"
            name="test_gpt_neo_2_7b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_gpt_neo_2_7b_inference', 'specific_test_case': 'test_gpt_neo_2_7b_inference', 'category': 'model_test', 'model_name': 'jax_gpt_neo_2.7b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/gpt_neo/gpt_neo_2_7b/test_gpt_neo_2_7b.py:45:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.llama.openllama_3b_v2.test_openllama_3b_v2"
            name="test_openllama3b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_openllama3b_inference', 'specific_test_case': 'test_openllama3b_inference', 'category': 'model_test', 'model_name': 'jax_open_llama_v2_3b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/llama/openllama_3b_v2/test_openllama_3b_v2.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.mbart50.large_many_to_many.test_mbart50_large_many_to_many"
            name="test_mbart50_large_many_to_many_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mbart50_large_many_to_many_inference', 'specific_test_case': 'test_mbart50_large_many_to_many_inference', 'category': 'model_test', 'model_name': 'jax_mbart50_large_many_to_many_nlp_summarization_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip" message="FAILED_FE_COMPILATION: OOMs in CI">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/mbart50/large_many_to_many/test_mbart50_large_many_to_many.py:44:
                FAILED_FE_COMPILATION: OOMs in CI</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.mistral_7b.v0_1.test_mistral_7b_v0_1"
            name="test_mistral_7b_v0_1_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mistral_7b_v0_1_inference', 'specific_test_case': 'test_mistral_7b_v0_1_inference', 'category': 'model_test', 'model_name': 'jax_mistral-7b_v0.1_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/mistral_7b/v0_1/test_mistral_7b_v0_1.py:45:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.mistral_7b.v0_1_tiny.test_mistral_7b_tiny_v0_1"
            name="test_mistral_7b_v0_1_tiny_inference" time="4.348">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mistral_7b_v0_1_tiny_inference', 'specific_test_case': 'test_mistral_7b_v0_1_tiny_inference', 'category': 'model_test', 'model_name': 'jax_mistral-7b_v0.1_tiny_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather' https://github.com/tenstorrent/tt-xla/issues/318" />
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.mistral_7b.v0_2_instruct.test_mistral_7b_v0_2_instruct"
            name="test_mistral_7b_v0_2_instruct_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mistral_7b_v0_2_instruct_inference', 'specific_test_case': 'test_mistral_7b_v0_2_instruct_inference', 'category': 'model_test', 'model_name': 'jax_mistral-7b_v0.2_instruct_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/mistral_7b/v0_2_instruct/test_mistral_7b_v0_2_instruct.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.mistral_7b.v0_3_instruct.test_mistral_7b_v0_3_instruct"
            name="test_mistral_7b_v0_3_instruct_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mistral_7b_v0_3_instruct_inference', 'specific_test_case': 'test_mistral_7b_v0_3_instruct_inference', 'category': 'model_test', 'model_name': 'jax_mistral-7b_v0.3_instruct_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="red" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/mistral_7b/v0_3_instruct/test_mistral_7b_v0_3_instruct.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.mlpmixer.test_mlpmixer"
            name="test_mlpmixer_inference" time="0.013">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mlpmixer_inference', 'specific_test_case': 'test_mlpmixer_inference', 'category': 'model_test', 'model_name': 'jax_mlpmixer_base_cv_image_cls_custom', 'run_mode': 'inference', 'bringup_status': 'FAILED_RUNTIME'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_RUNTIME: Out of Memory: Not enough space to allocate 12500992 B L1 buffer across 7 banks, where each bank needs to store 1785856 B(https://github.com/tenstorrent/tt-xla/issues/187)" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.mnist.cnn.dropout.test_mnist_cnn_dropout"
            name="test_mnist_cnn_dropout_inference" time="17.341">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mnist_cnn_dropout_inference', 'specific_test_case': 'test_mnist_cnn_dropout_inference', 'category': 'model_test', 'model_name': 'jax_mnist_cnn_dropout_cv_image_cls_custom', 'run_mode': 'inference', 'bringup_status': 'PASSED'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.mnist.cnn.nodropout.test_mnist_cnn_nodropout"
            name="test_mnist_cnn_nodropout_inference" time="11.190">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mnist_cnn_nodropout_inference', 'specific_test_case': 'test_mnist_cnn_nodropout_inference', 'category': 'model_test', 'model_name': 'jax_mnist_cnn_nodropout_cv_image_cls_custom', 'run_mode': 'inference', 'bringup_status': 'PASSED'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.mnist.mlp.test_mnist_mlp"
            name="test_mnist_mlp_inference[(256, 128, 64)]" time="3.673">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_mnist_mlp_inference', 'specific_test_case': 'test_mnist_mlp_inference[(256, 128, 64)]', 'category': 'model_test', 'model_name': 'jax_mnist_mlp_cv_image_cls_custom', 'run_mode': 'inference', 'bringup_status': 'PASSED'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.opt.opt_125m.test_125m"
            name="test_opt_125m_inference" time="15.557">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_opt_125m_inference', 'specific_test_case': 'test_opt_125m_inference', 'category': 'model_test', 'model_name': 'jax_opt_125m_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=4121164.25. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.opt.opt_1_3b.test_1_3b"
            name="test_opt_1_3b_inference" time="42.818">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_opt_1_3b_inference', 'specific_test_case': 'test_opt_1_3b_inference', 'category': 'model_test', 'model_name': 'jax_opt_1.3b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=2307070.75. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.opt.opt_2_7b.test_2_7b"
            name="test_opt_2_7b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_opt_2_7b_inference', 'specific_test_case': 'test_opt_2_7b_inference', 'category': 'model_test', 'model_name': 'jax_opt_2.7b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/opt/opt_2_7b/test_2_7b.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.opt.opt_350m.test_350m"
            name="test_opt_350m_inference" time="28.128">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_opt_350m_inference', 'specific_test_case': 'test_opt_350m_inference', 'category': 'model_test', 'model_name': 'jax_opt_350m_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=2040517.5. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.opt.opt_6_7b.test_6_7b"
            name="test_opt_6_7b_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_opt_6_7b_inference', 'specific_test_case': 'test_opt_6_7b_inference', 'category': 'model_test', 'model_name': 'jax_opt_6.7b_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/opt/opt_6_7b/test_6_7b.py:45:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.pegasus.large.test_pegasus_large"
            name="test_pegasus_large_inference" time="25.079">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_pegasus_large_inference', 'specific_test_case': 'test_pegasus_large_inference', 'category': 'model_test', 'model_name': 'jax_pegasus_large_nlp_summarization_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: 'ttir.scatter' op Dimension size to slice into must be 1 https://github.com/tenstorrent/tt-xla/issues/386 " />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.pegasus.xsum.test_pegasus_xsum"
            name="test_pegasus_xsum_inference" time="18.136">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_pegasus_xsum_inference', 'specific_test_case': 'test_pegasus_xsum_inference', 'category': 'model_test', 'model_name': 'jax_pegasus_xsum_nlp_summarization_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: 'ttir.scatter' op Dimension size to slice into must be 1 https://github.com/tenstorrent/tt-xla/issues/386 " />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_101.test_resnet_101"
            name="test_resnet_v1_5_101_inference" time="14.808">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_101_inference', 'specific_test_case': 'test_resnet_v1_5_101_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_101_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_152.test_resnet_152"
            name="test_resnet_v1_5_152_inference" time="4.090">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_152_inference', 'specific_test_case': 'test_resnet_v1_5_152_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_152_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_18.test_resnet_18"
            name="test_resnet_v1_5_18_inference" time="3.534">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_18_inference', 'specific_test_case': 'test_resnet_v1_5_18_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_18_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_26.test_resnet_26"
            name="test_resnet_v1_5_26_inference" time="0.946">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_26_inference', 'specific_test_case': 'test_resnet_v1_5_26_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_26_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_34.test_resnet_34"
            name="test_resnet_v1_5_34_inference" time="2.279">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_34_inference', 'specific_test_case': 'test_resnet_v1_5_34_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_34_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.resnet_v1_5.resnet_50.test_resnet_50"
            name="test_resnet_v1_5_50_inference" time="1.650">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_resnet_v1_5_50_inference', 'specific_test_case': 'test_resnet_v1_5_50_inference', 'category': 'model_test', 'model_name': 'jax_resnet_v1.5_50_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'stablehlo.reduce_window'" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.roberta.base.test_roberta_base"
            name="test_flax_roberta_base_inference" time="12.501">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_roberta_base_inference', 'specific_test_case': 'test_flax_roberta_base_inference', 'category': 'model_test', 'model_name': 'jax_roberta_base_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131044.359375. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.roberta.large.test_roberta_large"
            name="test_flax_roberta_large_inference" time="22.044">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_roberta_large_inference', 'specific_test_case': 'test_flax_roberta_large_inference', 'category': 'model_test', 'model_name': 'jax_roberta_large_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131078.359375. Required: atol=0.16" />
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.roberta_prelayernorm.efficient_mlm_m0_40.test_efficient_mlm_m0_40"
            name="test_flax_roberta_prelayernorm_inference" time="20.947">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_flax_roberta_prelayernorm_inference', 'specific_test_case': 'test_flax_roberta_prelayernorm_inference', 'category': 'model_test', 'model_name': 'jax_roberta_prelayernorm_efficient_mlm_m0.40_nlp_masked_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131048.65625. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.squeezebert.test_squeezebert"
            name="test_squeezebert_inference" time="2.357">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_squeezebert_inference', 'specific_test_case': 'test_squeezebert_inference', 'category': 'model_test', 'model_name': 'jax_squeezebert_uncased_nlp_masked_lm_custom', 'run_mode': 'inference', 'bringup_status': 'FAILED_TTMLIR_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="FAILED_TTMLIR_COMPILATION: failed to legalize operation 'ttir.gather'" />
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_base_patch16_224.test_vit_base_patch16_224"
            name="test_vit_base_patch16_224_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_base_patch16_224_inference', 'specific_test_case': 'test_vit_base_patch16_224_inference', 'category': 'model_test', 'model_name': 'jax_vit_base_patch16_224_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_base_patch16_224/test_vit_base_patch16_224.py:46:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_base_patch16_384.test_vit_base_patch16_384"
            name="test_vit_base_patch16_384_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_base_patch16_384_inference', 'specific_test_case': 'test_vit_base_patch16_384_inference', 'category': 'model_test', 'model_name': 'jax_vit_base_patch16_384_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_base_patch16_384/test_vit_base_patch16_384.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_base_patch32_224_in21k.test_vit_base_patch32_224_in21k"
            name="test_vit_base_patch32_224_in21k_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_base_patch32_224_in21k_inference', 'specific_test_case': 'test_vit_base_patch32_224_in21k_inference', 'category': 'model_test', 'model_name': 'jax_vit_base_patch32_224_in21k_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_base_patch32_224_in21k/test_vit_base_patch32_224_in21k.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_base_patch32_384.test_vit_base_patch32_384"
            name="test_vit_base_patch32_384_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_base_patch32_384_inference', 'specific_test_case': 'test_vit_base_patch32_384_inference', 'category': 'model_test', 'model_name': 'jax_vit_base_patch32_384_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_base_patch32_384/test_vit_base_patch32_384.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_huge_patch14_224_in21k.test_vit_huge_patch14_224_in21k"
            name="test_vit_huge_patch14_224_in21k_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_huge_patch14_224_in21k_inference', 'specific_test_case': 'test_vit_huge_patch14_224_in21k_inference', 'category': 'model_test', 'model_name': 'jax_vit_huge_patch14_224_in21k_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_huge_patch14_224_in21k/test_vit_huge_patch14_224_in21k.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_large_patch16_224.test_vit_large_patch16_224"
            name="test_vit_large_patch16_224_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_large_patch16_224_inference', 'specific_test_case': 'test_vit_large_patch16_224_inference', 'category': 'model_test', 'model_name': 'jax_vit_large_patch16_224_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_large_patch16_224/test_vit_large_patch16_224.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_large_patch16_384.test_vit_large_patch16_384"
            name="test_vit_large_patch16_384_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_large_patch16_384_inference', 'specific_test_case': 'test_vit_large_patch16_384_inference', 'category': 'model_test', 'model_name': 'jax_vit_large_patch16_384_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_large_patch16_384/test_vit_large_patch16_384.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_large_patch32_224_in21k.test_vit_large_patch32_224_in21k"
            name="test_vit_large_patch32_224_in21k_inference" time="0.001">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_large_patch32_224_in21k_inference', 'specific_test_case': 'test_vit_large_patch32_224_in21k_inference', 'category': 'model_test', 'model_name': 'jax_vit_large_patch32_224_in21k_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_large_patch32_224_in21k/test_vit_large_patch32_224_in21k.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase
            classname="tests.jax.single_chip.models.vit.vit_large_patch32_384.test_vit_large_patch32_384"
            name="test_vit_large_patch32_384_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_vit_large_patch32_384_inference', 'specific_test_case': 'test_vit_large_patch32_384_inference', 'category': 'model_test', 'model_name': 'jax_vit_large_patch32_384_cv_image_cls_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/vit/vit_large_patch32_384/test_vit_large_patch32_384.py:47:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
        <testcase classname="tests.jax.single_chip.models.xglm.xglm_564m.test_xglm_564m"
            name="test_xglm_564m_inference" time="38.461">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_xglm_564m_inference', 'specific_test_case': 'test_xglm_564m_inference', 'category': 'model_test', 'model_name': 'jax_xglm_564m_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=8313996.5. Required: atol=0.16." />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.xlm_roberta.base.test_xlm_roberta_base"
            name="test_xlm_roberta_base_inference" time="23.450">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_xlm_roberta_base_inference', 'specific_test_case': 'test_xlm_roberta_base_inference', 'category': 'model_test', 'model_name': 'jax_xlm-roberta_base_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'INCORRECT_RESULT'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.xfail"
                message="INCORRECT_RESULT: Atol comparison failed. Calculated: atol=131074.375. Required: atol=0.16" />
        </testcase>
        <testcase classname="tests.jax.single_chip.models.xlm_roberta.large.test_xlm_roberta_large"
            name="test_xlm_roberta_large_inference" time="0.000">
            <properties>
                <property name="tags"
                    value="{'test_name': 'test_xlm_roberta_large_inference', 'specific_test_case': 'test_xlm_roberta_large_inference', 'category': 'model_test', 'model_name': 'jax_xlm-roberta_large_nlp_causal_lm_huggingface', 'run_mode': 'inference', 'bringup_status': 'FAILED_FE_COMPILATION'}" />
                <property name="owner" value="tt-xla" />
                <property name="group" value="generality" />
            </properties>
            <skipped type="pytest.skip"
                message="FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)">/__w/tt-xla/tt-xla/tests/jax/single_chip/models/xlm_roberta/large/test_xlm_roberta_large.py:45:
                FAILED_FE_COMPILATION: OOMs in CI (https://github.com/tenstorrent/tt-xla/issues/186)</skipped>
        </testcase>
    </testsuite>
</testsuites>
